# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Upstream Coding Pittsburgh
title: Upstream Coding | Programming & Web Development Upskilling | Learn to code in Pittsburgh.
email: hello@upstreamcoding.com
tagline: Workers with basic programming skills and tech know-how are in-demand today. Upstream Coding can put higher-paying jobs in your reach.
description: Upskill with Upstream Coding. Part-time classes. Instructor-led. Programming & Coding Bootcamp in Pittsburgh. HTML, CSS, JavaScript, ES6+, React, Node, Kotlin, Python & Flask.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://upstreamcoding.com # the base hostname & protocol for your site, e.g. http://example.com
turbine_app_url: https://app.turbinelms.com
og_image: https://upstreamcoding.com/images/open-graph/in-demand-skills.jpg
s3bucket: https://s3.us-east-2.amazonaws.com/upstreamcoding.com
meta_keywords: [
  'candidate technical assessment',
  'evalutate technical skills',
  'assess coding skills',
  'whitelabel technical assessment',
  'modern website development',
  'coding bootcamp',
  'code school',
  'web developer coding bootcamp',
  'learn kotlin',
  'learn flask',
  'learn python',
  'learn node',
  'learn react',
  'learn html',
  'learn css',
  'learn javascript',
  'learn how to build a website',
  'learn frontend web development',
  'learn coding fast',
  'learn to code',
  'evening coding classes',
  'part time coding classes',
  'coding for adults',
  'website programming evening classes',
  'learn to code html',
  'learn to write code',
  'computer coding classes',
  'computer coding course',
  'computer coding training',
  'learn computer programming',
  'fastest way to learn web development',
  'building a website from scratch',
  'learn web development for beginners',
  'programs to learn coding',
  'coding courses for beginners',
  'learn coding for beginners',
  'learn to code course'
]

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

collections:
  pages:
    output: true

sass:
  style: compact # possible values: nested expanded compact compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
  - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
